/**:
  ros__parameters:
    cam_base_topic: camera/image_raw
    output_frame: ""
    marker_dict: 4X4_1000
    image_is_rectified: false
    image_sub_compressed: true
    publish_tf: false
    marker_size: 0.3
    image_sub_qos:
      reliability: 2
      durability: 2
      depth: 1

    pose_selector:
      strategy: REPROJECTION_ERROR
      debug: false
