name: down_camera
driver: usb_cam
port: /dev/video0
frame_id: bluerov/camera_down/optical_frame

width: 640
height: 360
framerate: 10.0
pixel_format: mjpeg2rgb
io_method: mmap

stonefish_topic: /bluerov/stonefish/down_camera/image_color

decimated:
  enabled: true
  width: 320
  height: 180
  decimation_x: 2
  decimation_y: 2
  offset_x: 0
  offset_y: 0
